In [3]:
import os
import pandas as pd
from IPython.display import display, Markdown
from tqdm.auto import tqdm # makes pretty progress bars
tqdm.pandas()
# this should be familiar!
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
full_data = pd.read_csv("tyler_trade_buys_only.csv")
full_data.head()

,date,trade_type,side,outcome,amount,price,total,title,user
0,2026-07-04 16:28,TRADE,BUY,No,3411.91,0.360000,1228.2876,US-Iran 60 day negotiation period extended?,0xe4de861d59e174d3d153a5968bc122c66f30c949
1,2026-07-04 16:19,TRADE,BUY,No,426.13,0.639695,272.5932,Strait of Hormuz traffic returns to normal by ...,0xe4de861d59e174d3d153a5968bc122c66f30c949
2,2026-07-04 16:18,TRADE,BUY,No,5000.00,0.485876,2429.3786,Strait of Hormuz traffic returns to normal by ...,0xe4de861d59e174d3d153a5968bc122c66f30c949
3,2026-07-04 16:17,TRADE,BUY,No,15.88,0.630000,10.0044,Strait of Hormuz traffic returns to normal by ...,0xe4de861d59e174d3d153a5968bc122c66f30c949
4,2026-07-04 16:17,TRADE,BUY,No,1603.98,0.630000,1010.5074,Strait of Hormuz traffic returns to normal by ...,0xe4de861d59e174d3d153a5968bc122c66f30c949

In [6]:
SIZE_OF_SAMPLE_FOR_HANDCODING = 100
##
## take a random sample to test our prompts against
text_column_name = "title" # change this to match your own dataset
full_data.dropna(subset=[text_column_name], inplace=True)
full_data["date"] = pd.to_datetime(full_data["date"])

# if you already did the handcoding, make sure the sample you're using is the right set.
WE_ALREADY_HANDCODED = os.path.exists("handcoded.csv")
if WE_ALREADY_HANDCODED:
  data_sample = pd.read_csv("handcoded.csv")
else:
  data_sample = full_data.sample(n=SIZE_OF_SAMPLE_FOR_HANDCODING, random_state=613)

data_sample = data_sample.copy() # avoid annoying warnings!

In [79]:
data_sample.to_csv("sample.csv")
data_sample

,Column1,date,trade_type,side,outcome,amount,price,total,title,user,ai_prompt,ai_guess,groundtruth
0,3082,7/10/2026 8:39,TRADE,BUY,BetBoom Team,13.770832,0.520,7.160833,Counter-Strike: FaZe vs BetBoom Team - Map 1 W...,0x96f795d0821b75a1c7f886b2c1cd49d108b7d6ae,\nYou are an expert in text interpretation and...,gaming,gaming
1,2921,6/9/2026 23:16,TRADE,BUY,Yes,25.020000,0.950,23.769000,Will Pamela Evette win the first round of the ...,0x2b9dbf4b6e0e11309a9d6d2a09b72f65f652adc0,\nYou are an expert in text interpretation and...,elections_global_and_domestic,elections_global_and_domestic
2,5588,7/4/2026 10:00,TRADE,BUY,Under,2000.000000,0.290,580.000000,Canada vs. Morocco: O/U 1.5,0x760907c8840491c8c86fddb843d3f1d801786c4e,\nYou are an expert in text interpretation and...,sports,sports
3,19168,7/10/2026 15:11,TRADE,BUY,Yes,166.670000,0.970,161.669900,Nathan Ngoy: 1+ shots,0x2843d543c60a54106f572ab74f0e2e04f293b3d2,\nYou are an expert in text interpretation and...,sports,sports
4,15089,2/6/2026 8:17,TRADE,BUY,Yes,5.555554,0.640,3.555555,"Will Trump say ""Charlie Kirk"" during the State...",0xb1a2757fd88d6f66255f53565ada24d875b257fe,\nYou are an expert in text interpretation and...,political_issues_except_us_elections,political_issues_except_us_elections
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,41257,6/27/2026 15:21,TRADE,BUY,Down,2.000000,0.500,1.000000,"Ethereum Up or Down - June 27, 3:20PM-3:25PM ET",0xcece2f5f75676c11ca0151a70507e045ca63a1e7,\nYou are an expert in text interpretation and...,crypto_currencies,crypto_currencies
96,13791,7/6/2026 16:47,TRADE,BUY,No,200.000000,0.670,134.000000,Will 60 ships transit the Strait of Hormuz on ...,0xeca0c0888e34df59589c67fbe53dc7f298b5e8f8,\nYou are an expert in text interpretation and...,geopolitics_except_elections,usa_iran_conflict
97,21106,6/25/2026 14:13,TRADE,BUY,Yes,18.000000,0.238,4.284000,Will Sweden win on 2026-06-25?,0xb8d8bc6acbe4b4596750b8ccd0f227eb7bd366a7,\nYou are an expert in text interpretation and...,sports,sports
98,31998,7/10/2026 15:12,TRADE,BUY,Yes,10.000000,0.520,5.200000,"Will Trump say ""Future President"" in July?",0x6b0ebbef2630b9a0da35594bf7ddd1911246e3ea,\nYou are an expert in text interpretation and...,political_issues_except_us_elections,political_issues_except_us_elections
99,15606,7/6/2026 21:59,TRADE,BUY,Egypt,5.779064,0.140,0.809069,Argentina vs. Egypt: Team to Advance,0xefde9ff487fae209ab6e3157a8acb4276f9c783d,\nYou are an expert in text interpretation and...,sports,sports

In [7]:
## prompt
## start with the one YOU tried in the LLM web interface
## don't worry, we'll adjust it later.
## Jeremy's is at the very bottom, if you need to reference it, but please come
##   up with your own.


# Be sure to list the categories (defined below!) with the magic phrase {categories}
prompt_base = """
You are an expert in text interpretation and classification.
Please read this prediction market title and determine which category best describes it. 
You must choose from the strict list of categories defined below. Return ONLY the exact Category Code, nothing else.

Categories and Definitions:
- sports: Any professional or collegiate sports events, games, or athlete performance metrics.
- political_issues_except_us_elections: Broader domestic political events, legislative outcomes, or policy decisions in the United States, excluding direct election results.
- gaming: Video games, esports tournaments, or gaming industry news.
- usa_iran_conflict: Any geopolitical, military, or diplomatic events specifically involving the United States and Iran. Developments in the straight of Hormuz included.
- elections_global_and_domestic: Political elections, including polling, candidates, and winners, both within the US and internationally.
- geopolitics_except_elections: All politics outside the USA, except elections and wars. International relations, global treaties, or global diplomatic events, excluding elections and wars.
- war_events: Military conflicts (excluding US-Iran). Examples of other ongoing wars are Russia-Ukraine, Israel-Lebanon. Israel-Iran counts as USA-Iran.
- tech: Technology companies, artificial intelligence, product launches, or science and space exploration.
- crypto_currencies: Blockchain technology, cryptocurrency prices, NFT markets, or decentralized finance (DeFi).
- pop_culture_and_entertainment: Celebrities, music, movies, awards shows, social media influencers, or viral internet events.
- crime: Criminal trials, verdicts, arrests, or legal proceedings.
- other: if it can not be defined by any other category. Resort to this only if necessary.

Here is the exact list of Category Codes to output: {categories}

Here is the market title: {market_title}
Do a really good job and make me proud. I will kick your grandma in the belly if you don't.

"""

from enum import Enum, IntEnum
# defining the categories "in a special way that will make the model follow directions"
# force the AI to ONLY guess fromn the options we ask you.
# you can change these names! (and perhaps should!)
# - the AI sees the _value_, not the key (it sees "broader_political_issues_except_us_election", not "other_politics")
# - the key is just for you -- a shorthand
# - some AIs have trouble with complicated names, so it's better to stick to lowercase, no special characters
#     (as of early June 2026 -- maybe this will be fixed)
# name them what they are because the llm needs to read them
class MarketCategoryOptions(str, Enum):
    sports = "sports"
    other_us_politics = "political_issues_except_us_elections"
    gaming = "gaming"
    us_iran_conflict = "usa_iran_conflict"
    elections = "elections_global_and_domestic"
    geopolitics = "geopolitics_except_elections"
    war = "war_events"
    tech = "tech"
    crypto = "crypto_currencies"
    pop_culture = "pop_culture_and_entertainment"
    crime = "crime"
    other = "other"


# for convenience, make a column in our dataframes with the prompt for each item
data_sample["ai_prompt"] = data_sample.apply(lambda row: prompt_base.format(
    market_title=row["title"],
    categories=", ".join(['"{}"'.format(opt.value) for opt in MarketCategoryOptions])
), axis="columns")
full_data["ai_prompt"] = full_data.apply(lambda row: prompt_base.format(
    market_title=row["title"],
    categories=", ".join(['"{}"'.format(opt.value) for opt in MarketCategoryOptions])
), axis="columns")

In [8]:
USE_OPENROUTER=True

from anthropic import Anthropic

if USE_OPENROUTER:
  from openrouter import OpenRouter
else:
  from openai import OpenAI
  from mistralai.client import Mistral

if USE_OPENROUTER:
  openrouter_client = OpenRouter(api_key=os.environ.get("OPENROUTER_API_KEY"))
else:
  openai_client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY_LEDE"))
  mistral_client = Mistral(api_key=os.environ.get("MISTRAL_API_KEY_LEDE"))
anthropic_client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY_LEDE"),)

In [9]:
data_sample["ai_prompt"].iloc[0]

'\nYou are an expert in text interpretation and classification.\nPlease read this prediction market title and determine which category best describes it. \nYou must choose from the strict list of categories defined below. Return ONLY the exact Category Code, nothing else.\n\nCategories and Definitions:\n- sports: Any professional or collegiate sports events, games, or athlete performance metrics.\n- political_issues_except_us_elections: Broader domestic political events, legislative outcomes, or policy decisions in the United States, excluding direct election results.\n- gaming: Video games, esports tournaments, or gaming industry news.\n- usa_iran_conflict: Any geopolitical, military, or diplomatic events specifically involving the United States and Iran. Developments in the straight of Hormuz included.\n- elections_global_and_domestic: Political elections, including polling, candidates, and winners, both within the US and internationally.\n- geopolitics_except_elections: All politics outside the USA, except elections and wars. International relations, global treaties, or global diplomatic events, excluding elections and wars.\n- war_events: Military conflicts (excluding US-Iran). Examples of other ongoing wars are Russia-Ukraine, Israel-Lebanon. Israel-Iran counts as USA-Iran.\n- tech: Technology companies, artificial intelligence, product launches, or science and space exploration.\n- crypto_currencies: Blockchain technology, cryptocurrency prices, NFT markets, or decentralized finance (DeFi).\n- pop_culture_and_entertainment: Celebrities, music, movies, awards shows, social media influencers, or viral internet events.\n- crime: Criminal trials, verdicts, arrests, or legal proceedings.\n- other: if it can not be defined by any other category. Resort to this only if necessary.\n\nHere is the exact list of Category Codes to output: "sports", "political_issues_except_us_elections", "gaming", "usa_iran_conflict", "elections_global_and_domestic", "geopolitics_except_elections", "war_events", "tech", "crypto_currencies", "pop_culture_and_entertainment", "crime", "other"\n\nHere is the market title: Counter-Strike: FaZe vs BetBoom Team - Map 1 Winner\nDo a really good job and make me proud. I will kick your grandma in the belly if you don\'t.\n\n'

In [10]:
from strip_tags import strip_tags
import tiktoken
def count_tokens(model, text):
  if "claude" in model and os.environ.get("ANTHROPIC_API_KEY_LEDE"):
    return anthropic_client.messages.count_tokens(model=model, messages=[{"content": text, "role": "user"}])
  elif "gpt" in model:
    encoding = tiktoken.encoding_for_model('gpt-4o') # most modern models use the same tokenizer
    tokens = encoding.encode(text)
    return len(tokens)
  else:
    return count_tokens("gpt-4o", text) # for estimation purposes, pretend mistral is chatgpt...

INPUT_TOKEN_COSTS = {
    "gpt-5-mini": 0.40 / 1_000_000,  # https://openai.com/api/pricing/
    "gpt-5.4-mini": 0.75 / 1_000_000,
    "gpt-5.4": 2.5 / 1_000_000,
    "gpt-5.5": 5 / 1_000_000,
    "gpt-5.4-nano": 0.2 / 1_000_000,
    "mistral-medium-latest": 1.5 / 1_000_000, # https://mistral.ai/pricing#api-pricing
    "mistral-large-latest":  0.5 / 1_000_000,  # No, I don't know why medium is more expensive than large.
    "claude-haiku-4.5": 1 / 1_000_000,
    "claude-sonnet-4.6": 3 / 1_000_000
}
# ignores outputs, since the model will output fairly little text

def estimate_cost(model, token_count):
    return token_count * INPUT_TOKEN_COSTS[model]

In [11]:
DEFAULT_MODEL_TO_USE = 'gpt-5.4-nano'
display(Markdown("Pick a model to use: \n" + "\n - ".join(list(INPUT_TOKEN_COSTS.keys()))))
MODEL_TO_USE = None

while MODEL_TO_USE not in INPUT_TOKEN_COSTS.keys():
  MODEL_TO_USE = input(f"type a model name (press enter for default: {DEFAULT_MODEL_TO_USE}): ").strip()
  if MODEL_TO_USE == "":
    MODEL_TO_USE = DEFAULT_MODEL_TO_USE

Pick a model to use:
gpt-5-mini
 - gpt-5.4-mini
 - gpt-5.4
 - gpt-5.5
 - gpt-5.4-nano
 - mistral-medium-latest
 - mistral-large-latest
 - claude-haiku-4.5
 - claude-sonnet-4.6

type a model name (press enter for default: gpt-5.4-nano):  claude-haiku-4.5

In [13]:
## cost estimation sample

count_tokens_for_our_model = lambda text: count_tokens(MODEL_TO_USE, text)

token_count_sample = count_tokens_for_our_model("SAMPLE RESPONSE SAMPLE RESPONSE".join(data_sample["ai_prompt"]))
"Sample would cost: ${:.2f}".format(estimate_cost(MODEL_TO_USE, token_count_sample))

'Sample would cost: $0.05'

In [14]:
## cost estimation for full dataset
token_count_full = count_tokens_for_our_model("SAMPLE RESPONSE SAMPLE RESPONSE".join(full_data["ai_prompt"]))
"Full dataset would cost: ${:.2f}".format(estimate_cost(MODEL_TO_USE, token_count_full))

'Full dataset would cost: $19.50'

In [15]:
## a lot of boilerplate for sending our prompt + tweet to the model and getting an answer
from pydantic import BaseModel


class MarketCategoryValidOptions(BaseModel):
  classification: MarketCategoryOptions

SYSTEM_PROMPT = "You are a helpful assistant"

def anthropic_classify(prompt_including_title):
    # put our prompt into the blob that OpenAI expects
    message = anthropic_client.messages.parse(
        max_tokens=1024,
        # system=SYSTEM_PROMPT, # causes trouble with structured outputs, oddly
        messages = [
            {
                "role": "user",
                "content": prompt_including_title,
            }
        ],
        model=MODEL_TO_USE,
        output_format=MarketCategoryOptions
    )
    return message.content[0].parsed_output.classification.value if message.content[0].parsed_output else None

def mistral_classify(prompt_including_title):
    # put our prompt into the blob that OpenAI expects
    chat_response = mistral_client.chat.parse(
      model=MODEL_TO_USE,
      messages=[
          {
              "role": "system",
              "content": SYSTEM_PROMPT
          },
          {
              "role": "user",
              "content": prompt_including_title
          },
      ],
      response_format=MarketCategoryOptions,
      max_tokens=256,
      temperature=0
    )
    return chat_response.choices[0].message.parsed.classification.value if chat_response.choices[0].message.parsed else None

def chatgpt_classify(prompt_including_title):
    # put our prompt into the blob that OpenAI expects
    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": prompt_including_title,
        }
    ]
    chat_completion = openai_client.responses.parse(
        input=messages,
        model=MODEL_TO_USE,
        text_format=MarketCategoryOptions,
    )

    # get the answer out of the blob that OpenAI returns.
    resp = chat_completion.output_parsed.classification.value if chat_completion.output_parsed else None
    return resp

openrouter_model_names = {
    "gpt-5-mini": "openai/gpt-5-mini",
    "gpt-5.4-mini": "openai/gpt-5.4-mini",
    "gpt-5.4": "openai/gpt-5.4",
    "gpt-5.5": "openai/gpt-5.5",
    "gpt-5.4-nano": "openai/gpt-5.4-nano",
    "mistral-medium-latest": "mistralai/mistral-medium-3-5",
    "mistral-large-latest": "mistralai/mistral-large-2512",
    "claude-haiku-4.5": "anthropic/claude-haiku-4.5",
    "claude-sonnet-4.6": "anthropic/claude-4.6-sonnet"
}
def openrouter_classify(prompt_including_title):
    response = openrouter_client.chat.send(
        model=openrouter_model_names[MODEL_TO_USE],
        messages=[
            {"role": "user", "content": prompt_including_title}
        ],
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "musk_tweet_classification",
                "strict": True,
                "schema": MarketCategoryValidOptions.model_json_schema(),
            },
        },
    )
    return  MarketCategoryValidOptions.model_validate_json(
        response.choices[0].message.content
    ).classification.value

def classify(prompt_including_title):
  "A wrapper for the provider-specific classification functions"
  if USE_OPENROUTER:
    return openrouter_classify(prompt_including_title)
  else:
    if "mistral" in MODEL_TO_USE == "mistral-medium-latest":
      return mistral_classify(prompt_including_title)
    elif "claude" in MODEL_TO_USE:
      return anthropic_classify(prompt_including_title)
    elif "gpt" in MODEL_TO_USE:
      return chatgpt_classify(prompt_including_title)
    else:
      raise ValueError("Unknown model")

In [102]:
# ask ChatGPT about each and every tweet IN THE SAMPLE, using the prompt we made above
data_sample["ai_guess"] = data_sample["ai_prompt"].progress_apply(classify)
display(Markdown("## Here are a few results. How good did we do?"))
with pd.option_context("display.max_colwidth", 500):
  display(
      data_sample[[text_column_name, "ai_guess"]].head(5)
  )

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

## Here are a few results. How good did we do?

,title,ai_guess
0,Counter-Strike: FaZe vs BetBoom Team - Map 1 Winner,gaming
1,Will Pamela Evette win the first round of the South Carolina Republican Governor Primary by less than 5%?,elections_global_and_domestic
2,Canada vs. Morocco: O/U 1.5,sports
3,Nathan Ngoy: 1+ shots,sports
4,"Will Trump say ""Charlie Kirk"" during the State of the Union address?",political_issues_except_us_elections

In [103]:
data_sample.head(10)

,Column1,date,trade_type,side,outcome,amount,price,total,title,user,ai_prompt,ai_guess,groundtruth
0,3082,7/10/2026 8:39,TRADE,BUY,BetBoom Team,13.770832,0.520,7.160833,Counter-Strike: FaZe vs BetBoom Team - Map 1 W...,0x96f795d0821b75a1c7f886b2c1cd49d108b7d6ae,\nYou are an expert in text interpretation and...,gaming,gaming
1,2921,6/9/2026 23:16,TRADE,BUY,Yes,25.020000,0.950,23.769000,Will Pamela Evette win the first round of the ...,0x2b9dbf4b6e0e11309a9d6d2a09b72f65f652adc0,\nYou are an expert in text interpretation and...,elections_global_and_domestic,elections_global_and_domestic
2,5588,7/4/2026 10:00,TRADE,BUY,Under,2000.000000,0.290,580.000000,Canada vs. Morocco: O/U 1.5,0x760907c8840491c8c86fddb843d3f1d801786c4e,\nYou are an expert in text interpretation and...,sports,sports
3,19168,7/10/2026 15:11,TRADE,BUY,Yes,166.670000,0.970,161.669900,Nathan Ngoy: 1+ shots,0x2843d543c60a54106f572ab74f0e2e04f293b3d2,\nYou are an expert in text interpretation and...,sports,sports
4,15089,2/6/2026 8:17,TRADE,BUY,Yes,5.555554,0.640,3.555555,"Will Trump say ""Charlie Kirk"" during the State...",0xb1a2757fd88d6f66255f53565ada24d875b257fe,\nYou are an expert in text interpretation and...,political_issues_except_us_elections,political_issues_except_us_elections
5,18625,7/9/2026 18:33,TRADE,BUY,Yes,5.140000,0.538,2.765320,Will Israel strike 4 countries in 2026?,0xa66790e2b0075e73c3781ddaf1d0b875a3aaceb3,\nYou are an expert in text interpretation and...,geopolitics_except_elections,war_events
6,17814,6/25/2026 16:26,TRADE,BUY,Yes,24.294116,0.170,4.129999,Will Sonia Backès be the next President of the...,0xc24fa1e0fda1552c830022807abd855aadbe220b,\nYou are an expert in text interpretation and...,elections_global_and_domestic,elections_global_and_domestic
7,35498,7/9/2026 11:19,TRADE,BUY,No,81.000000,0.885,71.685000,Will Elon Musk post 140-159 tweets from July 3...,0x6b17d237e6b7f74ce8171d6dc68e07bc21c803b2,\nYou are an expert in text interpretation and...,pop_culture_and_entertainment,pop_culture_and_entertainment
8,33775,7/10/2026 6:01,TRADE,BUY,No,10.000000,0.001,0.010000,Will OpenAI release a new frontier model on or...,0x66a1db98713015330a82f08273b682bee77e80d9,\nYou are an expert in text interpretation and...,tech,tech
9,13622,7/8/2026 17:25,TRADE,BUY,No,100.000000,0.260,26.000000,Will Graham Platner drop out by July 8?,0xeca0c0888e34df59589c67fbe53dc7f298b5e8f8,\nYou are an expert in text interpretation and...,elections_global_and_domestic,elections_global_and_domestic

In [104]:
#data_sample.to_csv("trades_for_hand_coding.csv") <-- we don't want to run this again (only 1st time)
data_sample.to_csv("handcoded.csv") #instead we overwrite the handcoded file

In [105]:
handcoded = pd.read_csv("handcoded.csv").set_index("title") # for some countries add `, delimiter=";"`
if "groundtruth" not in handcoded.columns:
  print("uh oh, your handcoded.csv doesn't have a column named groundtruth")
  assert "groundtruth" in handcoded.columns
if handcoded.groundtruth.isna().any() or (handcoded.groundtruth == '').any():
  print("uh oh, there are some blanks in your handcoded.csv's groundtruth column. go fix that!")

# if the ai_guess column got lost in the process... we'll grab it again
if "ai_guess" not in handcoded:
  handcoded = handcoded.merge(data_sample[["ai_guess"]], right_index=True, left_index=True)

In [106]:
from sklearn.metrics import accuracy_score
display(Markdown("Accuracy score: {:.1%}. Is that good?".format(
    accuracy_score(handcoded["groundtruth"], handcoded["ai_guess"])
)))

Accuracy score: 95.0%. Is that good?

In [107]:
# since running the AI over the whole dataset might cost a real amount of money
# this is just an extra check to make sure you want to do it.
# just hit enter (or type anything) to continue
# hit stop (to the left of this cell) to stop
okay_to_do_the_whole_thing = input()

In [ ]:
import time

def safe_classify(prompt_text):
    """A bodyguard function that retries the API if it fails, preventing crashes."""
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Try to run your original classify function
            return classify(prompt_text)
        except Exception as e:
            if attempt < max_retries - 1:
                # If it fails, wait a little bit (1s, 2s) and try again
                time.sleep(2 ** attempt) 
            else:
                # If it fails 3 times, don't crash! Just log an error in the CSV cell.
                # You can filter for these later to rerun them.
                return "API_ERROR"
                
# 1. Prepare your save file
output_filename = "ai_classified_tyler_trades_full.csv"
CHUNK_SIZE = 100

print(f"Starting classification for {len(full_data)} rows...")

# 2. Loop through the data in chunks of 100
for i in range(0, len(full_data), CHUNK_SIZE):
    
    # Slice out the current chunk
    chunk = full_data.iloc[i : i + CHUNK_SIZE].copy()
    
    # Run the AI on just these 100 rows
    print(f"\nProcessing rows {i} to {i + len(chunk)}...")
    chunk["ai_guess"] = chunk["ai_prompt"].progress_apply(safe_classify)
    
    # 3. Save the chunk to the CSV immediately
    # If it's the first chunk, write the headers. If it's a later chunk, just append to the bottom.
    if i == 0:
        chunk.to_csv(output_filename, index=False)
    else:
        chunk.to_csv(output_filename, index=False, mode='a', header=False)
        
    print(f"Saved rows {i} to {i + len(chunk)} to {output_filename}!")
    
    # Brief 2-second pause to let the API breathe and avoid rate limits
    time.sleep(2)

print("\n🎉 All 40,000 rows finished and securely saved!")

#BELOW IS THE CODE THAT JEREMY USED
#full_data["ai_guess"] = full_data["ai_prompt"].progress_apply(classify)
#full_data.to_csv("ai_classified_tyler_trades_full.csv", index=False)

Starting classification for 41291 rows...

Processing rows 0 to 100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:49<00:00,  1.69s/it]

Saved rows 0 to 100 to ai_classified_tyler_trades_full.csv!

Processing rows 100 to 200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 100 to 200 to ai_classified_tyler_trades_full.csv!

Processing rows 200 to 300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 200 to 300 to ai_classified_tyler_trades_full.csv!

Processing rows 300 to 400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 300 to 400 to ai_classified_tyler_trades_full.csv!

Processing rows 400 to 500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 400 to 500 to ai_classified_tyler_trades_full.csv!

Processing rows 500 to 600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.12s/it]

Saved rows 500 to 600 to ai_classified_tyler_trades_full.csv!

Processing rows 600 to 700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 600 to 700 to ai_classified_tyler_trades_full.csv!

Processing rows 700 to 800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:25<00:00,  1.45s/it]

Saved rows 700 to 800 to ai_classified_tyler_trades_full.csv!

Processing rows 800 to 900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 800 to 900 to ai_classified_tyler_trades_full.csv!

Processing rows 900 to 1000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 900 to 1000 to ai_classified_tyler_trades_full.csv!

Processing rows 1000 to 1100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 1000 to 1100 to ai_classified_tyler_trades_full.csv!

Processing rows 1100 to 1200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 1100 to 1200 to ai_classified_tyler_trades_full.csv!

Processing rows 1200 to 1300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 1200 to 1300 to ai_classified_tyler_trades_full.csv!

Processing rows 1300 to 1400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.15s/it]

Saved rows 1300 to 1400 to ai_classified_tyler_trades_full.csv!

Processing rows 1400 to 1500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 1400 to 1500 to ai_classified_tyler_trades_full.csv!

Processing rows 1500 to 1600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 1500 to 1600 to ai_classified_tyler_trades_full.csv!

Processing rows 1600 to 1700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 1600 to 1700 to ai_classified_tyler_trades_full.csv!

Processing rows 1700 to 1800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.15s/it]

Saved rows 1700 to 1800 to ai_classified_tyler_trades_full.csv!

Processing rows 1800 to 1900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 1800 to 1900 to ai_classified_tyler_trades_full.csv!

Processing rows 1900 to 2000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 1900 to 2000 to ai_classified_tyler_trades_full.csv!

Processing rows 2000 to 2100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 2000 to 2100 to ai_classified_tyler_trades_full.csv!

Processing rows 2100 to 2200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:01<00:00,  1.22s/it]

Saved rows 2100 to 2200 to ai_classified_tyler_trades_full.csv!

Processing rows 2200 to 2300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 2200 to 2300 to ai_classified_tyler_trades_full.csv!

Processing rows 2300 to 2400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 2300 to 2400 to ai_classified_tyler_trades_full.csv!

Processing rows 2400 to 2500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.12s/it]

Saved rows 2400 to 2500 to ai_classified_tyler_trades_full.csv!

Processing rows 2500 to 2600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 2500 to 2600 to ai_classified_tyler_trades_full.csv!

Processing rows 2600 to 2700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 2600 to 2700 to ai_classified_tyler_trades_full.csv!

Processing rows 2700 to 2800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:07<00:00,  1.27s/it]

Saved rows 2700 to 2800 to ai_classified_tyler_trades_full.csv!

Processing rows 2800 to 2900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 2800 to 2900 to ai_classified_tyler_trades_full.csv!

Processing rows 2900 to 3000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 2900 to 3000 to ai_classified_tyler_trades_full.csv!

Processing rows 3000 to 3100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 3000 to 3100 to ai_classified_tyler_trades_full.csv!

Processing rows 3100 to 3200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 3100 to 3200 to ai_classified_tyler_trades_full.csv!

Processing rows 3200 to 3300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 3200 to 3300 to ai_classified_tyler_trades_full.csv!

Processing rows 3300 to 3400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 3300 to 3400 to ai_classified_tyler_trades_full.csv!

Processing rows 3400 to 3500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 3400 to 3500 to ai_classified_tyler_trades_full.csv!

Processing rows 3500 to 3600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.04s/it]

Saved rows 3500 to 3600 to ai_classified_tyler_trades_full.csv!

Processing rows 3600 to 3700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 3600 to 3700 to ai_classified_tyler_trades_full.csv!

Processing rows 3700 to 3800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:05<00:00,  1.26s/it]

Saved rows 3700 to 3800 to ai_classified_tyler_trades_full.csv!

Processing rows 3800 to 3900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 3800 to 3900 to ai_classified_tyler_trades_full.csv!

Processing rows 3900 to 4000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:53<00:00,  1.13s/it]

Saved rows 3900 to 4000 to ai_classified_tyler_trades_full.csv!

Processing rows 4000 to 4100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:03<00:00,  1.23s/it]

Saved rows 4000 to 4100 to ai_classified_tyler_trades_full.csv!

Processing rows 4100 to 4200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:53<00:00,  1.14s/it]

Saved rows 4100 to 4200 to ai_classified_tyler_trades_full.csv!

Processing rows 4200 to 4300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:09<00:00,  1.30s/it]

Saved rows 4200 to 4300 to ai_classified_tyler_trades_full.csv!

Processing rows 4300 to 4400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:05<00:00,  1.26s/it]

Saved rows 4300 to 4400 to ai_classified_tyler_trades_full.csv!

Processing rows 4400 to 4500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:06<00:00,  1.27s/it]

Saved rows 4400 to 4500 to ai_classified_tyler_trades_full.csv!

Processing rows 4500 to 4600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 4500 to 4600 to ai_classified_tyler_trades_full.csv!

Processing rows 4600 to 4700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 4600 to 4700 to ai_classified_tyler_trades_full.csv!

Processing rows 4700 to 4800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 4700 to 4800 to ai_classified_tyler_trades_full.csv!

Processing rows 4800 to 4900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 4800 to 4900 to ai_classified_tyler_trades_full.csv!

Processing rows 4900 to 5000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 4900 to 5000 to ai_classified_tyler_trades_full.csv!

Processing rows 5000 to 5100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 5000 to 5100 to ai_classified_tyler_trades_full.csv!

Processing rows 5100 to 5200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 5100 to 5200 to ai_classified_tyler_trades_full.csv!

Processing rows 5200 to 5300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 5200 to 5300 to ai_classified_tyler_trades_full.csv!

Processing rows 5300 to 5400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 5300 to 5400 to ai_classified_tyler_trades_full.csv!

Processing rows 5400 to 5500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 5400 to 5500 to ai_classified_tyler_trades_full.csv!

Processing rows 5500 to 5600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 5500 to 5600 to ai_classified_tyler_trades_full.csv!

Processing rows 5600 to 5700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 5600 to 5700 to ai_classified_tyler_trades_full.csv!

Processing rows 5700 to 5800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 5700 to 5800 to ai_classified_tyler_trades_full.csv!

Processing rows 5800 to 5900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 5800 to 5900 to ai_classified_tyler_trades_full.csv!

Processing rows 5900 to 6000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 5900 to 6000 to ai_classified_tyler_trades_full.csv!

Processing rows 6000 to 6100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:56<00:00,  1.17s/it]

Saved rows 6000 to 6100 to ai_classified_tyler_trades_full.csv!

Processing rows 6100 to 6200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:57<00:00,  1.17s/it]

Saved rows 6100 to 6200 to ai_classified_tyler_trades_full.csv!

Processing rows 6200 to 6300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 6200 to 6300 to ai_classified_tyler_trades_full.csv!

Processing rows 6300 to 6400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 6300 to 6400 to ai_classified_tyler_trades_full.csv!

Processing rows 6400 to 6500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 6400 to 6500 to ai_classified_tyler_trades_full.csv!

Processing rows 6500 to 6600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 6500 to 6600 to ai_classified_tyler_trades_full.csv!

Processing rows 6600 to 6700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 6600 to 6700 to ai_classified_tyler_trades_full.csv!

Processing rows 6700 to 6800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.12s/it]

Saved rows 6700 to 6800 to ai_classified_tyler_trades_full.csv!

Processing rows 6800 to 6900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 6800 to 6900 to ai_classified_tyler_trades_full.csv!

Processing rows 6900 to 7000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 6900 to 7000 to ai_classified_tyler_trades_full.csv!

Processing rows 7000 to 7100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:56<00:00,  1.17s/it]

Saved rows 7000 to 7100 to ai_classified_tyler_trades_full.csv!

Processing rows 7100 to 7200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:55<00:00,  1.15s/it]

Saved rows 7100 to 7200 to ai_classified_tyler_trades_full.csv!

Processing rows 7200 to 7300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:01<00:00,  1.22s/it]

Saved rows 7200 to 7300 to ai_classified_tyler_trades_full.csv!

Processing rows 7300 to 7400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 7300 to 7400 to ai_classified_tyler_trades_full.csv!

Processing rows 7400 to 7500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 7400 to 7500 to ai_classified_tyler_trades_full.csv!

Processing rows 7500 to 7600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.15s/it]

Saved rows 7500 to 7600 to ai_classified_tyler_trades_full.csv!

Processing rows 7600 to 7700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:59<00:00,  1.19s/it]

Saved rows 7600 to 7700 to ai_classified_tyler_trades_full.csv!

Processing rows 7700 to 7800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 7700 to 7800 to ai_classified_tyler_trades_full.csv!

Processing rows 7800 to 7900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 7800 to 7900 to ai_classified_tyler_trades_full.csv!

Processing rows 7900 to 8000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 7900 to 8000 to ai_classified_tyler_trades_full.csv!

Processing rows 8000 to 8100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 8000 to 8100 to ai_classified_tyler_trades_full.csv!

Processing rows 8100 to 8200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 8100 to 8200 to ai_classified_tyler_trades_full.csv!

Processing rows 8200 to 8300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 8200 to 8300 to ai_classified_tyler_trades_full.csv!

Processing rows 8300 to 8400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 8300 to 8400 to ai_classified_tyler_trades_full.csv!

Processing rows 8400 to 8500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 8400 to 8500 to ai_classified_tyler_trades_full.csv!

Processing rows 8500 to 8600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 8500 to 8600 to ai_classified_tyler_trades_full.csv!

Processing rows 8600 to 8700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 8600 to 8700 to ai_classified_tyler_trades_full.csv!

Processing rows 8700 to 8800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 8700 to 8800 to ai_classified_tyler_trades_full.csv!

Processing rows 8800 to 8900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 8800 to 8900 to ai_classified_tyler_trades_full.csv!

Processing rows 8900 to 9000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 8900 to 9000 to ai_classified_tyler_trades_full.csv!

Processing rows 9000 to 9100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 9000 to 9100 to ai_classified_tyler_trades_full.csv!

Processing rows 9100 to 9200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 9100 to 9200 to ai_classified_tyler_trades_full.csv!

Processing rows 9200 to 9300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 9200 to 9300 to ai_classified_tyler_trades_full.csv!

Processing rows 9300 to 9400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:57<00:00,  1.18s/it]

Saved rows 9300 to 9400 to ai_classified_tyler_trades_full.csv!

Processing rows 9400 to 9500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 9400 to 9500 to ai_classified_tyler_trades_full.csv!

Processing rows 9500 to 9600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 9500 to 9600 to ai_classified_tyler_trades_full.csv!

Processing rows 9600 to 9700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 9600 to 9700 to ai_classified_tyler_trades_full.csv!

Processing rows 9700 to 9800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:06<00:00,  1.26s/it]

Saved rows 9700 to 9800 to ai_classified_tyler_trades_full.csv!

Processing rows 9800 to 9900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]

Saved rows 9800 to 9900 to ai_classified_tyler_trades_full.csv!

Processing rows 9900 to 10000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 9900 to 10000 to ai_classified_tyler_trades_full.csv!

Processing rows 10000 to 10100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 10000 to 10100 to ai_classified_tyler_trades_full.csv!

Processing rows 10100 to 10200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 10100 to 10200 to ai_classified_tyler_trades_full.csv!

Processing rows 10200 to 10300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.04s/it]

Saved rows 10200 to 10300 to ai_classified_tyler_trades_full.csv!

Processing rows 10300 to 10400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:37<00:00,  1.03it/s]

Saved rows 10300 to 10400 to ai_classified_tyler_trades_full.csv!

Processing rows 10400 to 10500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.01it/s]

Saved rows 10400 to 10500 to ai_classified_tyler_trades_full.csv!

Processing rows 10500 to 10600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 10500 to 10600 to ai_classified_tyler_trades_full.csv!

Processing rows 10600 to 10700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 10600 to 10700 to ai_classified_tyler_trades_full.csv!

Processing rows 10700 to 10800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 10700 to 10800 to ai_classified_tyler_trades_full.csv!

Processing rows 10800 to 10900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:58<00:00,  1.18s/it]

Saved rows 10800 to 10900 to ai_classified_tyler_trades_full.csv!

Processing rows 10900 to 11000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:58<00:00,  1.19s/it]

Saved rows 10900 to 11000 to ai_classified_tyler_trades_full.csv!

Processing rows 11000 to 11100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:56<00:00,  1.16s/it]

Saved rows 11000 to 11100 to ai_classified_tyler_trades_full.csv!

Processing rows 11100 to 11200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:36<00:00,  1.04it/s]

Saved rows 11100 to 11200 to ai_classified_tyler_trades_full.csv!

Processing rows 11200 to 11300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 11200 to 11300 to ai_classified_tyler_trades_full.csv!

Processing rows 11300 to 11400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:57<00:00,  1.18s/it]

Saved rows 11300 to 11400 to ai_classified_tyler_trades_full.csv!

Processing rows 11400 to 11500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 11400 to 11500 to ai_classified_tyler_trades_full.csv!

Processing rows 11500 to 11600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 11500 to 11600 to ai_classified_tyler_trades_full.csv!

Processing rows 11600 to 11700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:24<00:00,  1.45s/it]

Saved rows 11600 to 11700 to ai_classified_tyler_trades_full.csv!

Processing rows 11700 to 11800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 11700 to 11800 to ai_classified_tyler_trades_full.csv!

Processing rows 11800 to 11900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 11800 to 11900 to ai_classified_tyler_trades_full.csv!

Processing rows 11900 to 12000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 11900 to 12000 to ai_classified_tyler_trades_full.csv!

Processing rows 12000 to 12100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 12000 to 12100 to ai_classified_tyler_trades_full.csv!

Processing rows 12100 to 12200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 12100 to 12200 to ai_classified_tyler_trades_full.csv!

Processing rows 12200 to 12300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 12200 to 12300 to ai_classified_tyler_trades_full.csv!

Processing rows 12300 to 12400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 12300 to 12400 to ai_classified_tyler_trades_full.csv!

Processing rows 12400 to 12500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 12400 to 12500 to ai_classified_tyler_trades_full.csv!

Processing rows 12500 to 12600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 12500 to 12600 to ai_classified_tyler_trades_full.csv!

Processing rows 12600 to 12700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 12600 to 12700 to ai_classified_tyler_trades_full.csv!

Processing rows 12700 to 12800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 12700 to 12800 to ai_classified_tyler_trades_full.csv!

Processing rows 12800 to 12900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 12800 to 12900 to ai_classified_tyler_trades_full.csv!

Processing rows 12900 to 13000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 12900 to 13000 to ai_classified_tyler_trades_full.csv!

Processing rows 13000 to 13100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 13000 to 13100 to ai_classified_tyler_trades_full.csv!

Processing rows 13100 to 13200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 13100 to 13200 to ai_classified_tyler_trades_full.csv!

Processing rows 13200 to 13300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 13200 to 13300 to ai_classified_tyler_trades_full.csv!

Processing rows 13300 to 13400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 13300 to 13400 to ai_classified_tyler_trades_full.csv!

Processing rows 13400 to 13500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 13400 to 13500 to ai_classified_tyler_trades_full.csv!

Processing rows 13500 to 13600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 13500 to 13600 to ai_classified_tyler_trades_full.csv!

Processing rows 13600 to 13700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 13600 to 13700 to ai_classified_tyler_trades_full.csv!

Processing rows 13700 to 13800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:36<00:00,  1.03it/s]

Saved rows 13700 to 13800 to ai_classified_tyler_trades_full.csv!

Processing rows 13800 to 13900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 13800 to 13900 to ai_classified_tyler_trades_full.csv!

Processing rows 13900 to 14000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]

Saved rows 13900 to 14000 to ai_classified_tyler_trades_full.csv!

Processing rows 14000 to 14100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 14000 to 14100 to ai_classified_tyler_trades_full.csv!

Processing rows 14100 to 14200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 14100 to 14200 to ai_classified_tyler_trades_full.csv!

Processing rows 14200 to 14300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 14200 to 14300 to ai_classified_tyler_trades_full.csv!

Processing rows 14300 to 14400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.04s/it]

Saved rows 14300 to 14400 to ai_classified_tyler_trades_full.csv!

Processing rows 14400 to 14500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 14400 to 14500 to ai_classified_tyler_trades_full.csv!

Processing rows 14500 to 14600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:39<00:00,  1.00it/s]

Saved rows 14500 to 14600 to ai_classified_tyler_trades_full.csv!

Processing rows 14600 to 14700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.04s/it]

Saved rows 14600 to 14700 to ai_classified_tyler_trades_full.csv!

Processing rows 14700 to 14800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 14700 to 14800 to ai_classified_tyler_trades_full.csv!

Processing rows 14800 to 14900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 14800 to 14900 to ai_classified_tyler_trades_full.csv!

Processing rows 14900 to 15000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:39<00:00,  1.00it/s]

Saved rows 14900 to 15000 to ai_classified_tyler_trades_full.csv!

Processing rows 15000 to 15100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 15000 to 15100 to ai_classified_tyler_trades_full.csv!

Processing rows 15100 to 15200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 15100 to 15200 to ai_classified_tyler_trades_full.csv!

Processing rows 15200 to 15300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]

Saved rows 15200 to 15300 to ai_classified_tyler_trades_full.csv!

Processing rows 15300 to 15400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:37<00:00,  1.02it/s]

Saved rows 15300 to 15400 to ai_classified_tyler_trades_full.csv!

Processing rows 15400 to 15500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 15400 to 15500 to ai_classified_tyler_trades_full.csv!

Processing rows 15500 to 15600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:37<00:00,  1.03it/s]

Saved rows 15500 to 15600 to ai_classified_tyler_trades_full.csv!

Processing rows 15600 to 15700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:37<00:00,  1.02it/s]

Saved rows 15600 to 15700 to ai_classified_tyler_trades_full.csv!

Processing rows 15700 to 15800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:36<00:00,  1.03it/s]

Saved rows 15700 to 15800 to ai_classified_tyler_trades_full.csv!

Processing rows 15800 to 15900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 15800 to 15900 to ai_classified_tyler_trades_full.csv!

Processing rows 15900 to 16000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 15900 to 16000 to ai_classified_tyler_trades_full.csv!

Processing rows 16000 to 16100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 16000 to 16100 to ai_classified_tyler_trades_full.csv!

Processing rows 16100 to 16200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 16100 to 16200 to ai_classified_tyler_trades_full.csv!

Processing rows 16200 to 16300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:39<00:00,  1.00it/s]

Saved rows 16200 to 16300 to ai_classified_tyler_trades_full.csv!

Processing rows 16300 to 16400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 16300 to 16400 to ai_classified_tyler_trades_full.csv!

Processing rows 16400 to 16500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:39<00:00,  1.00it/s]

Saved rows 16400 to 16500 to ai_classified_tyler_trades_full.csv!

Processing rows 16500 to 16600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 16500 to 16600 to ai_classified_tyler_trades_full.csv!

Processing rows 16600 to 16700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 16600 to 16700 to ai_classified_tyler_trades_full.csv!

Processing rows 16700 to 16800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 16700 to 16800 to ai_classified_tyler_trades_full.csv!

Processing rows 16800 to 16900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 16800 to 16900 to ai_classified_tyler_trades_full.csv!

Processing rows 16900 to 17000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 16900 to 17000 to ai_classified_tyler_trades_full.csv!

Processing rows 17000 to 17100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 17000 to 17100 to ai_classified_tyler_trades_full.csv!

Processing rows 17100 to 17200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 17100 to 17200 to ai_classified_tyler_trades_full.csv!

Processing rows 17200 to 17300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 17200 to 17300 to ai_classified_tyler_trades_full.csv!

Processing rows 17300 to 17400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:13<00:00,  1.33s/it]

Saved rows 17300 to 17400 to ai_classified_tyler_trades_full.csv!

Processing rows 17400 to 17500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 17400 to 17500 to ai_classified_tyler_trades_full.csv!

Processing rows 17500 to 17600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 17500 to 17600 to ai_classified_tyler_trades_full.csv!

Processing rows 17600 to 17700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 17600 to 17700 to ai_classified_tyler_trades_full.csv!

Processing rows 17700 to 17800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 17700 to 17800 to ai_classified_tyler_trades_full.csv!

Processing rows 17800 to 17900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 17800 to 17900 to ai_classified_tyler_trades_full.csv!

Processing rows 17900 to 18000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 17900 to 18000 to ai_classified_tyler_trades_full.csv!

Processing rows 18000 to 18100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 18000 to 18100 to ai_classified_tyler_trades_full.csv!

Processing rows 18100 to 18200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 18100 to 18200 to ai_classified_tyler_trades_full.csv!

Processing rows 18200 to 18300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 18200 to 18300 to ai_classified_tyler_trades_full.csv!

Processing rows 18300 to 18400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 18300 to 18400 to ai_classified_tyler_trades_full.csv!

Processing rows 18400 to 18500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:00<00:00,  1.20s/it]

Saved rows 18400 to 18500 to ai_classified_tyler_trades_full.csv!

Processing rows 18500 to 18600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 18500 to 18600 to ai_classified_tyler_trades_full.csv!

Processing rows 18600 to 18700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 18600 to 18700 to ai_classified_tyler_trades_full.csv!

Processing rows 18700 to 18800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:39<00:00,  1.01it/s]

Saved rows 18700 to 18800 to ai_classified_tyler_trades_full.csv!

Processing rows 18800 to 18900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 18800 to 18900 to ai_classified_tyler_trades_full.csv!

Processing rows 18900 to 19000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 18900 to 19000 to ai_classified_tyler_trades_full.csv!

Processing rows 19000 to 19100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 19000 to 19100 to ai_classified_tyler_trades_full.csv!

Processing rows 19100 to 19200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]

Saved rows 19100 to 19200 to ai_classified_tyler_trades_full.csv!

Processing rows 19200 to 19300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 19200 to 19300 to ai_classified_tyler_trades_full.csv!

Processing rows 19300 to 19400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 19300 to 19400 to ai_classified_tyler_trades_full.csv!

Processing rows 19400 to 19500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 19400 to 19500 to ai_classified_tyler_trades_full.csv!

Processing rows 19500 to 19600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 19500 to 19600 to ai_classified_tyler_trades_full.csv!

Processing rows 19600 to 19700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 19600 to 19700 to ai_classified_tyler_trades_full.csv!

Processing rows 19700 to 19800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 19700 to 19800 to ai_classified_tyler_trades_full.csv!

Processing rows 19800 to 19900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 19800 to 19900 to ai_classified_tyler_trades_full.csv!

Processing rows 19900 to 20000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.05s/it]

Saved rows 19900 to 20000 to ai_classified_tyler_trades_full.csv!

Processing rows 20000 to 20100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.10s/it]

Saved rows 20000 to 20100 to ai_classified_tyler_trades_full.csv!

Processing rows 20100 to 20200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 20100 to 20200 to ai_classified_tyler_trades_full.csv!

Processing rows 20200 to 20300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 20200 to 20300 to ai_classified_tyler_trades_full.csv!

Processing rows 20300 to 20400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 20300 to 20400 to ai_classified_tyler_trades_full.csv!

Processing rows 20400 to 20500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 20400 to 20500 to ai_classified_tyler_trades_full.csv!

Processing rows 20500 to 20600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 20500 to 20600 to ai_classified_tyler_trades_full.csv!

Processing rows 20600 to 20700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 20600 to 20700 to ai_classified_tyler_trades_full.csv!

Processing rows 20700 to 20800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 20700 to 20800 to ai_classified_tyler_trades_full.csv!

Processing rows 20800 to 20900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 20800 to 20900 to ai_classified_tyler_trades_full.csv!

Processing rows 20900 to 21000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.14s/it]

Saved rows 20900 to 21000 to ai_classified_tyler_trades_full.csv!

Processing rows 21000 to 21100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 21000 to 21100 to ai_classified_tyler_trades_full.csv!

Processing rows 21100 to 21200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 21100 to 21200 to ai_classified_tyler_trades_full.csv!

Processing rows 21200 to 21300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 21200 to 21300 to ai_classified_tyler_trades_full.csv!

Processing rows 21300 to 21400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:56<00:00,  1.17s/it]

Saved rows 21300 to 21400 to ai_classified_tyler_trades_full.csv!

Processing rows 21400 to 21500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.15s/it]

Saved rows 21400 to 21500 to ai_classified_tyler_trades_full.csv!

Processing rows 21500 to 21600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 21500 to 21600 to ai_classified_tyler_trades_full.csv!

Processing rows 21600 to 21700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 21600 to 21700 to ai_classified_tyler_trades_full.csv!

Processing rows 21700 to 21800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:56<00:00,  1.16s/it]

Saved rows 21700 to 21800 to ai_classified_tyler_trades_full.csv!

Processing rows 21800 to 21900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 21800 to 21900 to ai_classified_tyler_trades_full.csv!

Processing rows 21900 to 22000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 21900 to 22000 to ai_classified_tyler_trades_full.csv!

Processing rows 22000 to 22100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 22000 to 22100 to ai_classified_tyler_trades_full.csv!

Processing rows 22100 to 22200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 22100 to 22200 to ai_classified_tyler_trades_full.csv!

Processing rows 22200 to 22300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 22200 to 22300 to ai_classified_tyler_trades_full.csv!

Processing rows 22300 to 22400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 22300 to 22400 to ai_classified_tyler_trades_full.csv!

Processing rows 22400 to 22500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.07s/it]

Saved rows 22400 to 22500 to ai_classified_tyler_trades_full.csv!

Processing rows 22500 to 22600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 22500 to 22600 to ai_classified_tyler_trades_full.csv!

Processing rows 22600 to 22700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:46<00:00,  1.06s/it]

Saved rows 22600 to 22700 to ai_classified_tyler_trades_full.csv!

Processing rows 22700 to 22800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.14s/it]

Saved rows 22700 to 22800 to ai_classified_tyler_trades_full.csv!

Processing rows 22800 to 22900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.04s/it]

Saved rows 22800 to 22900 to ai_classified_tyler_trades_full.csv!

Processing rows 22900 to 23000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 22900 to 23000 to ai_classified_tyler_trades_full.csv!

Processing rows 23000 to 23100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 23000 to 23100 to ai_classified_tyler_trades_full.csv!

Processing rows 23100 to 23200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

Saved rows 23100 to 23200 to ai_classified_tyler_trades_full.csv!

Processing rows 23200 to 23300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 23200 to 23300 to ai_classified_tyler_trades_full.csv!

Processing rows 23300 to 23400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 23300 to 23400 to ai_classified_tyler_trades_full.csv!

Processing rows 23400 to 23500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 23400 to 23500 to ai_classified_tyler_trades_full.csv!

Processing rows 23500 to 23600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 23500 to 23600 to ai_classified_tyler_trades_full.csv!

Processing rows 23600 to 23700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.01it/s]

Saved rows 23600 to 23700 to ai_classified_tyler_trades_full.csv!

Processing rows 23700 to 23800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]

Saved rows 23700 to 23800 to ai_classified_tyler_trades_full.csv!

Processing rows 23800 to 23900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 23800 to 23900 to ai_classified_tyler_trades_full.csv!

Processing rows 23900 to 24000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 23900 to 24000 to ai_classified_tyler_trades_full.csv!

Processing rows 24000 to 24100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 24000 to 24100 to ai_classified_tyler_trades_full.csv!

Processing rows 24100 to 24200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 24100 to 24200 to ai_classified_tyler_trades_full.csv!

Processing rows 24200 to 24300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 24200 to 24300 to ai_classified_tyler_trades_full.csv!

Processing rows 24300 to 24400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 24300 to 24400 to ai_classified_tyler_trades_full.csv!

Processing rows 24400 to 24500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:41<00:00,  1.01s/it]

Saved rows 24400 to 24500 to ai_classified_tyler_trades_full.csv!

Processing rows 24500 to 24600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.01s/it]

Saved rows 24500 to 24600 to ai_classified_tyler_trades_full.csv!

Processing rows 24600 to 24700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.10s/it]

Saved rows 24600 to 24700 to ai_classified_tyler_trades_full.csv!

Processing rows 24700 to 24800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:49<00:00,  1.09s/it]

Saved rows 24700 to 24800 to ai_classified_tyler_trades_full.csv!

Processing rows 24800 to 24900...

 99%|██████████████████████████████████████████████████████████████████████████████████████▏| 99/100 [02:13<00:04,  4.48s/it]

In [18]:
import time
check_df = pd.read_csv("ai_classified_tyler_trades_full.csv")
print(f"Safely saved rows on disk: {len(check_df)}")

START_ROW = len(check_df)  # Tell the script to skip the finished rows
output_filename = "ai_classified_tyler_trades_full.csv"
CHUNK_SIZE = 100

print(f"Resuming classification from row {START_ROW} out of {len(full_data)}...")

def safe_classify(prompt_text):
    """A bodyguard function that retries the API if it fails, preventing crashes."""
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Try to run your original classify function
            return classify(prompt_text)
        except Exception as e:
            if attempt < max_retries - 1:
                # If it fails, wait a little bit (1s, 2s) and try again
                time.sleep(2 ** attempt) 
            else:
                # If it fails 3 times, don't crash! Just log an error in the CSV cell.
                # You can filter for these later to rerun them.
                return "API_ERROR"

# ==========================================
# THE RESUME LOOP
# ==========================================
for i in range(START_ROW, len(full_data), CHUNK_SIZE):
    
    # Slice out the chunk starting from our resume point
    chunk = full_data.iloc[i : i + CHUNK_SIZE].copy()
    
    print(f"\nProcessing rows {i} to {i + len(chunk)}...")
    
    # Run the bodyguard function
    chunk["ai_guess"] = chunk["ai_prompt"].progress_apply(safe_classify)
    
    # FIX: Because we are resuming, we ALWAYS append ('a') and NEVER write headers
    chunk.to_csv(output_filename, index=False, mode='a', header=False)
    
    print(f"Saved rows {i} to {i + len(chunk)} to {output_filename}!")
    
    # Let the API breathe
    time.sleep(2)

print("\n🎉 All 40,000 rows finished and securely saved!")

Safely saved rows on disk: 24900
Resuming classification from row 24900 out of 41291...

Processing rows 24900 to 25000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:52<00:00,  1.12s/it]

Saved rows 24900 to 25000 to ai_classified_tyler_trades_full.csv!

Processing rows 25000 to 25100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 25000 to 25100 to ai_classified_tyler_trades_full.csv!

Processing rows 25100 to 25200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:59<00:00,  1.19s/it]

Saved rows 25100 to 25200 to ai_classified_tyler_trades_full.csv!

Processing rows 25200 to 25300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.03s/it]

Saved rows 25200 to 25300 to ai_classified_tyler_trades_full.csv!

Processing rows 25300 to 25400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:08<00:00,  1.29s/it]

Saved rows 25300 to 25400 to ai_classified_tyler_trades_full.csv!

Processing rows 25400 to 25500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:43<00:00,  1.03s/it]

Saved rows 25400 to 25500 to ai_classified_tyler_trades_full.csv!

Processing rows 25500 to 25600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.01it/s]

Saved rows 25500 to 25600 to ai_classified_tyler_trades_full.csv!

Processing rows 25600 to 25700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:40<00:00,  1.00s/it]

Saved rows 25600 to 25700 to ai_classified_tyler_trades_full.csv!

Processing rows 25700 to 25800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:50<00:00,  1.11s/it]

Saved rows 25700 to 25800 to ai_classified_tyler_trades_full.csv!

Processing rows 25800 to 25900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:44<00:00,  1.04s/it]

Saved rows 25800 to 25900 to ai_classified_tyler_trades_full.csv!

Processing rows 25900 to 26000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 25900 to 26000 to ai_classified_tyler_trades_full.csv!

Processing rows 26000 to 26100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 26000 to 26100 to ai_classified_tyler_trades_full.csv!

Processing rows 26100 to 26200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.11s/it]

Saved rows 26100 to 26200 to ai_classified_tyler_trades_full.csv!

Processing rows 26200 to 26300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:52<00:00,  1.73s/it]

Saved rows 26200 to 26300 to ai_classified_tyler_trades_full.csv!

Processing rows 26300 to 26400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:10<00:00,  1.31s/it]

Saved rows 26300 to 26400 to ai_classified_tyler_trades_full.csv!

Processing rows 26400 to 26500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.09s/it]

Saved rows 26400 to 26500 to ai_classified_tyler_trades_full.csv!

Processing rows 26500 to 26600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 26500 to 26600 to ai_classified_tyler_trades_full.csv!

Processing rows 26600 to 26700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.06s/it]

Saved rows 26600 to 26700 to ai_classified_tyler_trades_full.csv!

Processing rows 26700 to 26800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.07s/it]

Saved rows 26700 to 26800 to ai_classified_tyler_trades_full.csv!

Processing rows 26800 to 26900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:55<00:00,  1.15s/it]

Saved rows 26800 to 26900 to ai_classified_tyler_trades_full.csv!

Processing rows 26900 to 27000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00,  1.05s/it]

Saved rows 26900 to 27000 to ai_classified_tyler_trades_full.csv!

Processing rows 27000 to 27100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:54<00:00,  1.15s/it]

Saved rows 27000 to 27100 to ai_classified_tyler_trades_full.csv!

Processing rows 27100 to 27200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:48<00:00,  1.08s/it]

Saved rows 27100 to 27200 to ai_classified_tyler_trades_full.csv!

Processing rows 27200 to 27300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:47<00:00,  1.08s/it]

Saved rows 27200 to 27300 to ai_classified_tyler_trades_full.csv!

Processing rows 27300 to 27400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:34<00:00,  1.54s/it]

Saved rows 27300 to 27400 to ai_classified_tyler_trades_full.csv!

Processing rows 27400 to 27500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:58<00:00,  3.59s/it]

Saved rows 27400 to 27500 to ai_classified_tyler_trades_full.csv!

Processing rows 27500 to 27600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:57<00:00,  3.57s/it]

Saved rows 27500 to 27600 to ai_classified_tyler_trades_full.csv!

Processing rows 27600 to 27700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:57<00:00,  3.57s/it]

Saved rows 27600 to 27700 to ai_classified_tyler_trades_full.csv!

Processing rows 27700 to 27800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [06:16<00:00,  3.77s/it]

Saved rows 27700 to 27800 to ai_classified_tyler_trades_full.csv!

Processing rows 27800 to 27900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.50s/it]

Saved rows 27800 to 27900 to ai_classified_tyler_trades_full.csv!

Processing rows 27900 to 28000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.52s/it]

Saved rows 27900 to 28000 to ai_classified_tyler_trades_full.csv!

Processing rows 28000 to 28100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:55<00:00,  3.55s/it]

Saved rows 28000 to 28100 to ai_classified_tyler_trades_full.csv!

Processing rows 28100 to 28200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.50s/it]

Saved rows 28100 to 28200 to ai_classified_tyler_trades_full.csv!

Processing rows 28200 to 28300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.50s/it]

Saved rows 28200 to 28300 to ai_classified_tyler_trades_full.csv!

Processing rows 28300 to 28400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.46s/it]

Saved rows 28300 to 28400 to ai_classified_tyler_trades_full.csv!

Processing rows 28400 to 28500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:43<00:00,  3.43s/it]

Saved rows 28400 to 28500 to ai_classified_tyler_trades_full.csv!

Processing rows 28500 to 28600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:41<00:00,  3.42s/it]

Saved rows 28500 to 28600 to ai_classified_tyler_trades_full.csv!

Processing rows 28600 to 28700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.46s/it]

Saved rows 28600 to 28700 to ai_classified_tyler_trades_full.csv!

Processing rows 28700 to 28800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:43<00:00,  3.44s/it]

Saved rows 28700 to 28800 to ai_classified_tyler_trades_full.csv!

Processing rows 28800 to 28900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:42<00:00,  3.43s/it]

Saved rows 28800 to 28900 to ai_classified_tyler_trades_full.csv!

Processing rows 28900 to 29000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:42<00:00,  3.43s/it]

Saved rows 28900 to 29000 to ai_classified_tyler_trades_full.csv!

Processing rows 29000 to 29100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:47<00:00,  3.47s/it]

Saved rows 29000 to 29100 to ai_classified_tyler_trades_full.csv!

Processing rows 29100 to 29200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:44<00:00,  3.45s/it]

Saved rows 29100 to 29200 to ai_classified_tyler_trades_full.csv!

Processing rows 29200 to 29300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.46s/it]

Saved rows 29200 to 29300 to ai_classified_tyler_trades_full.csv!

Processing rows 29300 to 29400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.47s/it]

Saved rows 29300 to 29400 to ai_classified_tyler_trades_full.csv!

Processing rows 29400 to 29500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:47<00:00,  3.48s/it]

Saved rows 29400 to 29500 to ai_classified_tyler_trades_full.csv!

Processing rows 29500 to 29600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.52s/it]

Saved rows 29500 to 29600 to ai_classified_tyler_trades_full.csv!

Processing rows 29600 to 29700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.46s/it]

Saved rows 29600 to 29700 to ai_classified_tyler_trades_full.csv!

Processing rows 29700 to 29800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.52s/it]

Saved rows 29700 to 29800 to ai_classified_tyler_trades_full.csv!

Processing rows 29800 to 29900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:54<00:00,  3.55s/it]

Saved rows 29800 to 29900 to ai_classified_tyler_trades_full.csv!

Processing rows 29900 to 30000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:53<00:00,  3.54s/it]

Saved rows 29900 to 30000 to ai_classified_tyler_trades_full.csv!

Processing rows 30000 to 30100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:47<00:00,  3.48s/it]

Saved rows 30000 to 30100 to ai_classified_tyler_trades_full.csv!

Processing rows 30100 to 30200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.52s/it]

Saved rows 30100 to 30200 to ai_classified_tyler_trades_full.csv!

Processing rows 30200 to 30300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [06:00<00:00,  3.60s/it]

Saved rows 30200 to 30300 to ai_classified_tyler_trades_full.csv!

Processing rows 30300 to 30400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.51s/it]

Saved rows 30300 to 30400 to ai_classified_tyler_trades_full.csv!

Processing rows 30400 to 30500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:53<00:00,  3.53s/it]

Saved rows 30400 to 30500 to ai_classified_tyler_trades_full.csv!

Processing rows 30500 to 30600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.47s/it]

Saved rows 30500 to 30600 to ai_classified_tyler_trades_full.csv!

Processing rows 30600 to 30700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.51s/it]

Saved rows 30600 to 30700 to ai_classified_tyler_trades_full.csv!

Processing rows 30700 to 30800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:53<00:00,  3.53s/it]

Saved rows 30700 to 30800 to ai_classified_tyler_trades_full.csv!

Processing rows 30800 to 30900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:56<00:00,  3.57s/it]

Saved rows 30800 to 30900 to ai_classified_tyler_trades_full.csv!

Processing rows 30900 to 31000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:54<00:00,  3.55s/it]

Saved rows 30900 to 31000 to ai_classified_tyler_trades_full.csv!

Processing rows 31000 to 31100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:55<00:00,  3.55s/it]

Saved rows 31000 to 31100 to ai_classified_tyler_trades_full.csv!

Processing rows 31100 to 31200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.53s/it]

Saved rows 31100 to 31200 to ai_classified_tyler_trades_full.csv!

Processing rows 31200 to 31300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.50s/it]

Saved rows 31200 to 31300 to ai_classified_tyler_trades_full.csv!

Processing rows 31300 to 31400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [06:01<00:00,  3.61s/it]

Saved rows 31300 to 31400 to ai_classified_tyler_trades_full.csv!

Processing rows 31400 to 31500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.52s/it]

Saved rows 31400 to 31500 to ai_classified_tyler_trades_full.csv!

Processing rows 31500 to 31600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.53s/it]

Saved rows 31500 to 31600 to ai_classified_tyler_trades_full.csv!

Processing rows 31600 to 31700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.51s/it]

Saved rows 31600 to 31700 to ai_classified_tyler_trades_full.csv!

Processing rows 31700 to 31800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:48<00:00,  3.49s/it]

Saved rows 31700 to 31800 to ai_classified_tyler_trades_full.csv!

Processing rows 31800 to 31900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 31800 to 31900 to ai_classified_tyler_trades_full.csv!

Processing rows 31900 to 32000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.52s/it]

Saved rows 31900 to 32000 to ai_classified_tyler_trades_full.csv!

Processing rows 32000 to 32100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.51s/it]

Saved rows 32000 to 32100 to ai_classified_tyler_trades_full.csv!

Processing rows 32100 to 32200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:48<00:00,  3.48s/it]

Saved rows 32100 to 32200 to ai_classified_tyler_trades_full.csv!

Processing rows 32200 to 32300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:47<00:00,  3.47s/it]

Saved rows 32200 to 32300 to ai_classified_tyler_trades_full.csv!

Processing rows 32300 to 32400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 32300 to 32400 to ai_classified_tyler_trades_full.csv!

Processing rows 32400 to 32500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.47s/it]

Saved rows 32400 to 32500 to ai_classified_tyler_trades_full.csv!

Processing rows 32500 to 32600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.45s/it]

Saved rows 32500 to 32600 to ai_classified_tyler_trades_full.csv!

Processing rows 32600 to 32700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 32600 to 32700 to ai_classified_tyler_trades_full.csv!

Processing rows 32700 to 32800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.46s/it]

Saved rows 32700 to 32800 to ai_classified_tyler_trades_full.csv!

Processing rows 32800 to 32900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:48<00:00,  3.49s/it]

Saved rows 32800 to 32900 to ai_classified_tyler_trades_full.csv!

Processing rows 32900 to 33000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 32900 to 33000 to ai_classified_tyler_trades_full.csv!

Processing rows 33000 to 33100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 33000 to 33100 to ai_classified_tyler_trades_full.csv!

Processing rows 33100 to 33200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.53s/it]

Saved rows 33100 to 33200 to ai_classified_tyler_trades_full.csv!

Processing rows 33200 to 33300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.50s/it]

Saved rows 33200 to 33300 to ai_classified_tyler_trades_full.csv!

Processing rows 33300 to 33400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 33300 to 33400 to ai_classified_tyler_trades_full.csv!

Processing rows 33400 to 33500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.45s/it]

Saved rows 33400 to 33500 to ai_classified_tyler_trades_full.csv!

Processing rows 33500 to 33600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:46<00:00,  3.46s/it]

Saved rows 33500 to 33600 to ai_classified_tyler_trades_full.csv!

Processing rows 33600 to 33700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:54<00:00,  3.55s/it]

Saved rows 33600 to 33700 to ai_classified_tyler_trades_full.csv!

Processing rows 33700 to 33800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:48<00:00,  3.49s/it]

Saved rows 33700 to 33800 to ai_classified_tyler_trades_full.csv!

Processing rows 33800 to 33900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:47<00:00,  3.47s/it]

Saved rows 33800 to 33900 to ai_classified_tyler_trades_full.csv!

Processing rows 33900 to 34000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:48<00:00,  3.49s/it]

Saved rows 33900 to 34000 to ai_classified_tyler_trades_full.csv!

Processing rows 34000 to 34100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:45<00:00,  3.46s/it]

Saved rows 34000 to 34100 to ai_classified_tyler_trades_full.csv!

Processing rows 34100 to 34200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:50<00:00,  3.51s/it]

Saved rows 34100 to 34200 to ai_classified_tyler_trades_full.csv!

Processing rows 34200 to 34300...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:52<00:00,  3.53s/it]

Saved rows 34200 to 34300 to ai_classified_tyler_trades_full.csv!

Processing rows 34300 to 34400...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.51s/it]

Saved rows 34300 to 34400 to ai_classified_tyler_trades_full.csv!

Processing rows 34400 to 34500...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.49s/it]

Saved rows 34400 to 34500 to ai_classified_tyler_trades_full.csv!

Processing rows 34500 to 34600...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.51s/it]

Saved rows 34500 to 34600 to ai_classified_tyler_trades_full.csv!

Processing rows 34600 to 34700...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:49<00:00,  3.50s/it]

Saved rows 34600 to 34700 to ai_classified_tyler_trades_full.csv!

Processing rows 34700 to 34800...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.51s/it]

Saved rows 34700 to 34800 to ai_classified_tyler_trades_full.csv!

Processing rows 34800 to 34900...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.52s/it]

Saved rows 34800 to 34900 to ai_classified_tyler_trades_full.csv!

Processing rows 34900 to 35000...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:51<00:00,  3.51s/it]

Saved rows 34900 to 35000 to ai_classified_tyler_trades_full.csv!

Processing rows 35000 to 35100...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:53<00:00,  3.54s/it]

Saved rows 35000 to 35100 to ai_classified_tyler_trades_full.csv!

Processing rows 35100 to 35200...

100%|██████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:55<00:00,  3.55s/it]

Saved rows 35100 to 35200 to ai_classified_tyler_trades_full.csv!

Processing rows 35200 to 35300...

  2%|█▊                                                                                      | 2/100 [00:07<06:27,  3.96s/it]

KeyboardInterrupt:

In [19]:
df_saved = pd.read_csv("ai_classified_tyler_trades_full.csv")

In [20]:
print(f"Rows successfully analyzed: {len(df_saved)}")

Rows successfully analyzed: 35200