In [1]:
import pandas as pd

In [4]:
cd "spreadsheets"

C:\Users\arvid\Desktop\GitHub\Lede Project 2\spreadsheets

In [7]:
df1 = pd.read_csv("chart_ai_guess.csv")
df1

                                ai_guess  count
0                                 sports   6609
1          elections_global_and_domestic   4636
2                      usa_iran_conflict   4069
3                                   tech   2451
4                      crypto_currencies   2247
5   political_issues_except_us_elections   1838
6          pop_culture_and_entertainment   1732
7                                  other   1218
8           geopolitics_except_elections   1173
9                                  crime    496
10                            war_events    475
11                                gaming    440

In [5]:
df = pd.read_csv("ai_guess_w_money.csv")

,Unnamed: 0,ai_guess,total_bets,total_money,percentage of bets,percentage of USD
0,0,crime,496,6.460362e+04,24.134531,1.933801
1,1,crypto_currencies,2247,8.509955e+04,16.929594,2.547312
2,2,elections_global_and_domestic,4636,6.484989e+05,14.859042,19.411727
3,3,gaming,440,5.036929e+04,8.950482,1.507720
4,4,geopolitics_except_elections,1173,1.605617e+05,8.205521,4.806144
5,5,other,1218,5.478175e+04,6.711949,1.639800
6,6,political_issues_except_us_elections,1838,2.452495e+05,6.324861,7.341131
7,7,pop_culture_and_entertainment,1732,1.034009e+05,4.447853,3.095133
8,8,sports,6609,1.024547e+06,4.283523,30.668096
9,9,tech,2451,2.808636e+05,1.811277,8.407181
10,10,usa_iran_conflict,4069,5.942248e+05,1.734590,17.787121
11,11,war_events,475,2.855792e+04,1.606778,0.854833

In [11]:
df ["percentage of bets"] = (df["total_bets"] / df["total_bets"].sum()) * 100

,Unnamed: 0,ai_guess,total_bets,total_money,percentage of bets,percentage of USD
0,0,crime,496,6.460362e+04,1.811277,1.933801
1,1,crypto_currencies,2247,8.509955e+04,8.205521,2.547312
2,2,elections_global_and_domestic,4636,6.484989e+05,16.929594,19.411727
3,3,gaming,440,5.036929e+04,1.606778,1.507720
4,4,geopolitics_except_elections,1173,1.605617e+05,4.283523,4.806144
5,5,other,1218,5.478175e+04,4.447853,1.639800
6,6,political_issues_except_us_elections,1838,2.452495e+05,6.711949,7.341131
7,7,pop_culture_and_entertainment,1732,1.034009e+05,6.324861,3.095133
8,8,sports,6609,1.024547e+06,24.134531,30.668096
9,9,tech,2451,2.808636e+05,8.950482,8.407181
10,10,usa_iran_conflict,4069,5.942248e+05,14.859042,17.787121
11,11,war_events,475,2.855792e+04,1.734590,0.854833

In [14]:
df.drop(columns="Unnamed: 0", inplace=True)
df

,ai_guess,total_bets,total_money,percentage of bets,percentage of USD
0,crime,496,6.460362e+04,1.811277,1.933801
1,crypto_currencies,2247,8.509955e+04,8.205521,2.547312
2,elections_global_and_domestic,4636,6.484989e+05,16.929594,19.411727
3,gaming,440,5.036929e+04,1.606778,1.507720
4,geopolitics_except_elections,1173,1.605617e+05,4.283523,4.806144
5,other,1218,5.478175e+04,4.447853,1.639800
6,political_issues_except_us_elections,1838,2.452495e+05,6.711949,7.341131
7,pop_culture_and_entertainment,1732,1.034009e+05,6.324861,3.095133
8,sports,6609,1.024547e+06,24.134531,30.668096
9,tech,2451,2.808636e+05,8.950482,8.407181
10,usa_iran_conflict,4069,5.942248e+05,14.859042,17.787121
11,war_events,475,2.855792e+04,1.734590,0.854833

In [15]:
df.to_csv("ai_guess_w_money.csv")